package database.relationships;

import org.neo4j.ogm.annotation.GeneratedValue;
import org.neo4j.ogm.annotation.Id;

/**
 * Base class for Neo4j relationships
 * Contains parameter ID, generated by Neo4j database
 */
public class Relationship {
    @Id
    @GeneratedValue
    private Long id;

    public Long getId() {
        return this.id;
    }
    public void setId(Long id) {
        this.id = id;
    }
}
